Employees/Models/ErrorViewModel.cs
namespace Employees.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Employees/Controllers/ChildrenController.cs
using Application.Mediatr.Child.Commands;
using Application.Mediatr.Child.Queries;
using Application.Mediatr.EmployeeDropDown.Queries;
using Domain.Entities;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Employees.Controllers
{
    public class ChildrenController : Controller
    {
        private readonly IMediator _mediator;

        public ChildrenController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _mediator.Send(new GetAllChildrenQuery()));
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _mediator.Send(new GetChildrenByIdQuery() { Id = id }));
        }

        public IActionResult Create()
        {
            var employeeList = _mediator.Send(new GetEmployeeDropDownQuery()).Result;
            ViewData["EmployeeList"] = employeeList.Select(e => new SelectListItem
            {
                Text = e.Name,
                Value = e.Id.ToString()
            });
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateChildrenCommand command)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _mediator.Send(command);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }
            var employeeList = _mediator.Send(new GetEmployeeDropDownQuery()).Result;
            ViewData["EmployeeList"] = employeeList.Select(e => new SelectListItem
            {
                Text = e.Name,
                Value = e.Id.ToString()
            });
            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            var children = await _mediator.Send(new GetChildrenByIdQuery() { Id = id});
            var employeeList = await _mediator.Send(new GetEmployeeDropDownQuery());

            ViewData["EmployeeList"] = employeeList.Select(e => new SelectListItem
            {
                Text = e.Name,
                Value = e.Id.ToString()
            });

            var command = new UpdateChildrenCommand
            {
                Id = children.Id,
                LastName = children.LastName,
                Name = children.Name,
                MiddleName = children.MiddleName,
                BirthDate = children.BirthDate,
                EmployeeId = children.EmployeeId,
                Employee = children.Employee
            };
            return View(command);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UpdateChildrenCommand command)
        {
            if (id != command.Id)
            {
                return BadRequest();
            }

            try
            {
                if (ModelState.IsValid)
                {
                    await _mediator.Send(command);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }

            var employeeList = await _mediator.Send(new GetEmployeeDropDownQuery());
            ViewData["EmployeeList"] = employeeList.Select(e => new SelectListItem
            {
                Text = e.Name,
                Value = e.Id.ToString()
            });
            return View(command);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _mediator.Send(new DeleteChildrenCommand() { Id = id });
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to delete. ");
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Employees/Controllers/HomeController.cs
using Application.Mediatr.Employ.Commands;
using Application.Mediatr.Employ.Queries;
using Employees.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Threading.Tasks;

namespace Employees.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMediator _mediator;

        public HomeController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _mediator.Send(new GetAllEmploeesQuery()));
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _mediator.Send(new GetEmployeeByIdQuery() { Id = id }));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateEmployeeCommand command)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _mediator.Send(command);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }
            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            return View(await _mediator.Send(new GetEmployeeByIdQuery() { Id = id }));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UpdateEmployeeCommand command)
        {
            if (id != command.Id)
            {
                return BadRequest();
            }

            try
            {
                if (ModelState.IsValid)
                {
                    await _mediator.Send(command);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }
            return View(command);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _mediator.Send(new DeleteEmployeeCommand() { Id = id });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to delete. ");
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ViewChild(int id)
        {
            return View(await _mediator.Send(new GetEmployeeByIdQuery() { Id = id }));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Employees/Views/Children/Create.cshtml
@using Application.Mediatr.Child.Commands;
@using Domain.Entities;
@model CreateChildrenCommand

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Children</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" asp-items="@(ViewData["EmployeeList"] as IEnumerable<SelectListItem>)" class="form-control">
                    <option value="">--Select Employee--</option>
                </select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

Employees/Views/Children/Details.cshtml
@model Domain.Entities.Children
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h1>@Model.Name</h1>
<hr />
<div>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            Parent
        </dt>
            <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.LastName)
            @Html.DisplayFor(model => model.Employee.Name)
            @Html.DisplayFor(model => model.Employee.MiddleName)
            </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

Employees/Views/Children/Edit.cshtml
@using Application.Mediatr.Child.Commands;
@model UpdateChildrenCommand

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Children</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <input asp-for="Id" class="form-control" type="hidden" />
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" asp-items="@(ViewData["EmployeeList"] as IEnumerable<SelectListItem>)" class="form-control">
                    <option value="">--Select Employee--</option>
                </select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

Employees/Views/Children/Index.cshtml
@model IEnumerable<Domain.Entities.Children>


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container p-3 bg-white">
    <div class="row pt-4 py-2">
        <div class="col-6">
            <h2 class="text-primary">Employee List</h2>
        </div>
        <div class="col text-right">
            <a asp-controller="Home" asp-action="Index" class="btn btn-info mx-2">
                Children List
            </a>
            <a asp-action="Create" class="btn btn-success">Create New Children</a>
        </div>
    </div>

    <br />
    <table class="table table-bordered table-stripped py-2" style="width:100%">
        <thead>
            <tr>
                <th>
                    Last Name
                </th>
                <th>
                    Name
                </th>
                <th>
                    Middle Name
                </th>
                <th>
                    Birth Date
                </th>
                <th>
                    Parent
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                @foreach (var obj in Model)
                {
                    <tr>
                        <td nowrap>@obj.LastName</td>
                        <td nowrap>@obj.Name</td>
                        <td nowrap>@obj.MiddleName</td>
                        <td nowrap>@obj.BirthDate</td>
                        <td nowrap>@obj.Employee.Name @obj.Employee.LastName</td>

                        <td class="text-center">
                            <div class="w-65 btn-group" role="group">
                                <a asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary">
                                    Edit
                                </a>
                                <a asp-route-Id="@obj.Id" asp-action="Details" class="btn btn-primary">
                                    Details
                                </a>
                                <a asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger">
                                    Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <p>No product exist.</p>
            }
        </tbody>
    </table>
</div>

Employees/Views/Home/Create.cshtml
@model Domain.Entities.Employee

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Employee</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

Employees/Views/Home/Details.cshtml
@model Domain.Entities.Employee
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Model.Name</h1>
<hr />
<div>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class="col-sm-2">
            Child
        </dt>
        @foreach (var item in Model.Children)
        {
            <dd style="width: 10rem; padding-right:2px;">
                    @Html.DisplayFor(model => item.LastName)
                    @Html.DisplayFor(model => item.Name)
                    @Html.DisplayFor(model => item.MiddleName)
            </dd>
        }
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

Employees/Views/Home/Edit.cshtml
@model Domain.Entities.Employee

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Employee</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <input asp-for="Id" class="form-control" type="hidden" />
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

Employees/Views/Home/Index.cshtml
@model IEnumerable<Domain.Entities.Employee>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container p-3 bg-white">
    <div class="row pt-4 py-2">
        <div class="col-6">
            <h2 class="text-primary">Employee List</h2>
        </div>
        <div class="col text-right">
            <a asp-controller="Children" asp-action="Index" class="btn btn-info mx-2">
                Children List
            </a>
            <a asp-action="Create" class="btn btn-success">Create New Employees</a>
        </div>
    </div>

    <br />
        <table class="table table-bordered table-stripped py-2" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Last Name
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Middle Name
                    </th>
                    <th>
                        Birth Date
                    </th>
                    <th>
                        Position
                    </th>
                    <th>
                        Number of children
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() > 0)
                {
                    @foreach (var obj in Model)
                    {
                    <tr>
                        <td nowrap>@obj.LastName</td>
                        <td nowrap>@obj.Name</td>
                        <td nowrap>@obj.MiddleName</td>
                        <td nowrap>@obj.BirthDate</td>
                        <td nowrap>@obj.Position</td>
                        <td nowrap>@obj.Children.Count()</td>

                        <td class="text-center">
                            <div class="w-65 btn-group" role="group">
                                <a asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary">
                                    Edit
                                </a>
                                <a asp-route-Id="@obj.Id" asp-action="Details" class="btn btn-primary">
                                    Details
                                </a>
                                <a asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger">
                                    Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                    }
                }
            else
            {
                <p>No product exist.</p>
            }
            </tbody>
        </table>
</div>

Employees/Views/Home/ViewChild.cshtml
@model Domain.Entities.Employee
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Model.Name</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            Child
        </dt>
            @foreach (var item in Model.Children)
            {
                    <dd style="width: 10rem; padding-right:2px;">
                        @Html.DisplayFor(model => item.LastName)
                        @Html.DisplayFor(model => item.Name)
                        @Html.DisplayFor(model => item.MiddleName)
                    </dd>
            }
    </dl>
</div>
<div>
    <a asp-controller="Children" asp-action="Create" class="btn btn-secondary">Create Children</a>
    <a asp-controller="Children" asp-action="Index" class="btn btn-secondary">View all children</a>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

Employees/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employees</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employees</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Children" asp-action="Index">Children</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Employees - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>